# Form implementation generated from reading ui file 'D:\Final_Project_HTM\ui\AboutUs\AboutUs.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        MainWindow.resize(1009, 605)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"    border: none")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 0, 141, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: transparent;\n"
"\n"
"    border: none")
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\AboutUs\\../images/logoreal.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButtonShowtimes = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonShowtimes.setGeometry(QtCore.QRect(10, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonShowtimes.setFont(font)
        self.pushButtonShowtimes.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"    border: none")
        self.pushButtonShowtimes.setObjectName("pushButtonShowtimes")
        self.pushButtonDiscounts = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDiscounts.setGeometry(QtCore.QRect(780, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDiscounts.setFont(font)
        self.pushButtonDiscounts.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"    border: none")
        self.pushButtonDiscounts.setObjectName("pushButtonDiscounts")
        self.pushButtonAboutUs = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonAboutUs.setGeometry(QtCore.QRect(890, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAboutUs.setFont(font)
        self.pushButtonAboutUs.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 0);\n"
"    border: none")
        self.pushButtonAboutUs.setObjectName("pushButtonAboutUs")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 100, 1001, 461))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setKerning(True)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("QScrollBar::sub-line:vertical {\n"
"    border:none;\n"
"    background-color:rgb(59,59,90);\n"
"    height: 15px;\n"
"    border-top-left-radius:7px;\n"
"    border-top-right-radius:7px;\n"
"    subcontrol-position:top;\n"
"    subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    background-color:rgb(255,0,127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"    background-color:rgb(185,0,92);\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border:none;\n"
"    background-color:rgb(59,59,90);\n"
"    height: 15px;\n"
"    border-top-left-radius:7px;\n"
"    border-top-right-radius:7px;\n"
"    subcontrol-position:bottom;\n"
"    subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    background-color:rgb(255,0,127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"    background-color:rgb(185,0,92);\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical{\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
"    background: none;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border:none;\n"
"    background-color:rgb(59,59,90);\n"
"    height: 15px;\n"
"    border-top-left-radius:7px;\n"
"    border-top-right-radius:7px;\n"
"    subcontrol-position:top;\n"
"    subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"    background-color:rgb(255,0,127);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"    background-color:rgb(185,0,92);\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border:none;\n"
"    background-color:rgb(59,59,90);\n"
"    height: 15px;\n"
"    border-top-left-radius:7px;\n"
"    border-top-right-radius:7px;\n"
"    subcontrol-position:bottom;\n"
"    subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"    background-color:rgb(255,0,127);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"    background-color:rgb(185,0,92);\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal{\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal{\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 988, 3012))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(100, 3000))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setStyleSheet("    border: none")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 20, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: transparent;\n"
"   \n"
"color: rgb(255, 255, 255);\n"
" border: none")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(50, 1290, 201, 221))
        self.label_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_4.setText("")
        self.label_4.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_4.setPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\AboutUs\\../../images/AboutUs5.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(50, 730, 411, 231))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\AboutUs\\../../images/AboutUs1.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(520, 500, 411, 221))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\AboutUs\\../../images/AboutUs3.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(520, 990, 411, 221))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\AboutUs\\../../images/AboutUs7.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(-100, -10, 1161, 331))
        self.label_2.setStyleSheet("\n"
"background-color: rgb(123, 0, 0);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\AboutUs\\../../images/AboutUs4.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_12 = QtWidgets.QLabel(parent=self.frame)
        self.label_12.setGeometry(QtCore.QRect(20, 60, 501, 31))
        self.label_12.setStyleSheet("background-color: transparent;\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"    border: none")
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(parent=self.frame)
        self.label_14.setGeometry(QtCore.QRect(40, 340, 761, 61))
        self.label_14.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label_14.setObjectName("label_14")
        self.label_16 = QtWidgets.QLabel(parent=self.frame)
        self.label_16.setGeometry(QtCore.QRect(40, 400, 831, 20))
        self.label_16.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.frame)
        self.label_17.setGeometry(QtCore.QRect(140, 500, 291, 51))
        self.label_17.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.label_19 = QtWidgets.QLabel(parent=self.frame)
        self.label_19.setGeometry(QtCore.QRect(380, 1270, 221, 61))
        self.label_19.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.frame)
        self.label_20.setGeometry(QtCore.QRect(480, 800, 481, 20))
        self.label_20.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_20.setObjectName("label_20")
        self.line_2 = QtWidgets.QFrame(parent=self.frame)
        self.line_2.setGeometry(QtCore.QRect(580, 1510, 118, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButtonLearnMore1 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonLearnMore1.setGeometry(QtCore.QRect(210, 650, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLearnMore1.setFont(font)
        self.pushButtonLearnMore1.setStyleSheet(" background-color: transparent; /* Transparent background */\n"
"    color: white;                  /* White text */\n"
"    border: 2px solid white;       /* White border */\n"
"    border-radius: 20px;           /* Rounded corners */\n"
"    padding: 10px 20px;            /* Padding inside the button */\n"
"    font-size: 16px;               /* Font size */\n"
"    font-weight: bold; \n"
"  background-color: rgba(0, 0, 0,0.1);")
        self.pushButtonLearnMore1.setObjectName("pushButtonLearnMore1")
        self.label_22 = QtWidgets.QLabel(parent=self.frame)
        self.label_22.setGeometry(QtCore.QRect(90, 550, 391, 41))
        self.label_22.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.frame)
        self.label_23.setGeometry(QtCore.QRect(480, 860, 451, 20))
        self.label_23.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(parent=self.frame)
        self.label_25.setGeometry(QtCore.QRect(-10, 1560, 1071, 411))
        self.label_25.setStyleSheet("\n"
"background-color: rgb(123, 0, 0);")
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\AboutUs\\../../images/AboutUs2.jpg"))
        self.label_25.setScaledContents(True)
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.line_3 = QtWidgets.QFrame(parent=self.frame)
        self.line_3.setGeometry(QtCore.QRect(40, 60, 118, 3))
        self.line_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_21 = QtWidgets.QLabel(parent=self.frame)
        self.label_21.setGeometry(QtCore.QRect(40, 420, 831, 20))
        self.label_21.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_21.setObjectName("label_21")
        self.label_18 = QtWidgets.QLabel(parent=self.frame)
        self.label_18.setGeometry(QtCore.QRect(150, 990, 251, 51))
        self.label_18.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.label_26 = QtWidgets.QLabel(parent=self.frame)
        self.label_26.setGeometry(QtCore.QRect(650, 750, 121, 41))
        self.label_26.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.label_26.setObjectName("label_26")
        self.label_28 = QtWidgets.QLabel(parent=self.frame)
        self.label_28.setGeometry(QtCore.QRect(80, 580, 411, 21))
        self.label_28.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(parent=self.frame)
        self.label_29.setGeometry(QtCore.QRect(80, 600, 431, 21))
        self.label_29.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(parent=self.frame)
        self.label_30.setGeometry(QtCore.QRect(480, 820, 471, 20))
        self.label_30.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(parent=self.frame)
        self.label_31.setGeometry(QtCore.QRect(480, 840, 491, 20))
        self.label_31.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_31.setObjectName("label_31")
        self.pushButtonLearnMore2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonLearnMore2.setGeometry(QtCore.QRect(640, 900, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLearnMore2.setFont(font)
        self.pushButtonLearnMore2.setStyleSheet(" background-color: transparent; /* Transparent background */\n"
"    color: white;                  /* White text */\n"
"    border: 2px solid white;       /* White border */\n"
"    border-radius: 20px;           /* Rounded corners */\n"
"    padding: 10px 20px;            /* Padding inside the button */\n"
"    font-size: 16px;               /* Font size */\n"
"    font-weight: bold; \n"
"  background-color: rgba(0, 0, 0,0.1);")
        self.pushButtonLearnMore2.setObjectName("pushButtonLearnMore2")
        self.label_24 = QtWidgets.QLabel(parent=self.frame)
        self.label_24.setGeometry(QtCore.QRect(30, 1070, 471, 20))
        self.label_24.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_24.setObjectName("label_24")
        self.label_32 = QtWidgets.QLabel(parent=self.frame)
        self.label_32.setGeometry(QtCore.QRect(30, 1050, 481, 20))
        self.label_32.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_32.setObjectName("label_32")
        self.label_27 = QtWidgets.QLabel(parent=self.frame)
        self.label_27.setGeometry(QtCore.QRect(30, 1090, 471, 20))
        self.label_27.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_27.setObjectName("label_27")
        self.pushButtonLearnMore3 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonLearnMore3.setGeometry(QtCore.QRect(180, 1130, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLearnMore3.setFont(font)
        self.pushButtonLearnMore3.setStyleSheet(" background-color: transparent; /* Transparent background */\n"
"    color: white;                  /* White text */\n"
"    border: 2px solid white;       /* White border */\n"
"    border-radius: 20px;           /* Rounded corners */\n"
"    padding: 10px 20px;            /* Padding inside the button */\n"
"    font-size: 16px;               /* Font size */\n"
"    font-weight: bold; \n"
"  background-color: rgba(0, 0, 0,0.1);")
        self.pushButtonLearnMore3.setObjectName("pushButtonLearnMore3")
        self.label_33 = QtWidgets.QLabel(parent=self.frame)
        self.label_33.setGeometry(QtCore.QRect(290, 1370, 471, 20))
        self.label_33.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(parent=self.frame)
        self.label_34.setGeometry(QtCore.QRect(290, 1330, 421, 20))
        self.label_34.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_34.setObjectName("label_34")
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_7.setGeometry(QtCore.QRect(740, 1280, 191, 221))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\AboutUs\\../../images/AboutUs8.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_35 = QtWidgets.QLabel(parent=self.frame)
        self.label_35.setGeometry(QtCore.QRect(290, 1350, 421, 20))
        self.label_35.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_35.setObjectName("label_35")
        self.label_8 = QtWidgets.QLabel(parent=self.frame)
        self.label_8.setGeometry(QtCore.QRect(290, 1390, 91, 16))
        self.label_8.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.pushButtonLearnMore4 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonLearnMore4.setGeometry(QtCore.QRect(420, 1440, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonLearnMore4.setFont(font)
        self.pushButtonLearnMore4.setStyleSheet(" background-color: transparent; /* Transparent background */\n"
"    color: white;                  /* White text */\n"
"    border: 2px solid white;       /* White border */\n"
"    border-radius: 20px;           /* Rounded corners */\n"
"    padding: 10px 20px;            /* Padding inside the button */\n"
"    font-size: 16px;               /* Font size */\n"
"    font-weight: bold; \n"
"  background-color: rgba(0, 0, 0,0.1);")
        self.pushButtonLearnMore4.setObjectName("pushButtonLearnMore4")
        self.label_44 = QtWidgets.QLabel(parent=self.frame)
        self.label_44.setGeometry(QtCore.QRect(-10, 1980, 1001, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_44.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.pushButtonfb = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonfb.setGeometry(QtCore.QRect(430, 2030, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonfb.setFont(font)
        self.pushButtonfb.setStyleSheet("background-color:  rgb(255, 255, 255);\n"
"color:rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"    padding: 5px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\AboutUs\\../../images/fb.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonfb.setIcon(icon1)
        self.pushButtonfb.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonfb.setAutoRepeatDelay(305)
        self.pushButtonfb.setObjectName("pushButtonfb")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 2070, 981, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: transparent;\n"
"\n"
"    border: none")
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\AboutUs\\../../images/logoreal.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_42 = QtWidgets.QLabel(parent=self.frame)
        self.label_42.setGeometry(QtCore.QRect(0, 2120, 981, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_42.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(parent=self.frame)
        self.label_43.setGeometry(QtCore.QRect(0, 2160, 981, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_43.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label.raise_()
        self.label_12.raise_()
        self.label_14.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.line_2.raise_()
        self.pushButtonLearnMore1.raise_()
        self.label_22.raise_()
        self.label_23.raise_()
        self.label_25.raise_()
        self.line_3.raise_()
        self.label_21.raise_()
        self.label_18.raise_()
        self.label_26.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.label_31.raise_()
        self.pushButtonLearnMore2.raise_()
        self.label_24.raise_()
        self.label_32.raise_()
        self.label_27.raise_()
        self.pushButtonLearnMore3.raise_()
        self.label_33.raise_()
        self.label_34.raise_()
        self.label_7.raise_()
        self.label_35.raise_()
        self.label_8.raise_()
        self.pushButtonLearnMore4.raise_()
        self.label_44.raise_()
        self.pushButtonfb.raise_()
        self.pushButton_4.raise_()
        self.label_42.raise_()
        self.label_43.raise_()
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 60, 1001, 1))
        self.line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(130, 75, 86, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("border:none\n"
"")
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButtonTicket = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonTicket.setGeometry(QtCore.QRect(720, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonTicket.setFont(font)
        self.pushButtonTicket.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"color: rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"    padding: 5px")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\AboutUs\\../../images/ic_ticket.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonTicket.setIcon(icon3)
        self.pushButtonTicket.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonTicket.setObjectName("pushButtonTicket")
        self.pushButtonBuyPop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBuyPop.setGeometry(QtCore.QRect(860, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonBuyPop.setFont(font)
        self.pushButtonBuyPop.setStyleSheet("background-color: rgb(111, 56, 193);\n"
"color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\AboutUs\\../../images/ic_popcorn.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonBuyPop.setIcon(icon4)
        self.pushButtonBuyPop.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonBuyPop.setAutoRepeatDelay(305)
        self.pushButtonBuyPop.setObjectName("pushButtonBuyPop")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 0, 141, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: transparent;\n"
"\n"
"    border: none")
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1009, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HOME"))
        self.pushButtonShowtimes.setText(_translate("MainWindow", "Showtimes"))
        self.pushButtonDiscounts.setText(_translate("MainWindow", "Discounts"))
        self.pushButtonAboutUs.setText(_translate("MainWindow", "About Us"))
        self.label_3.setText(_translate("MainWindow", "About GFLIX"))
        self.label_12.setText(_translate("MainWindow", "Find out more about our company, an industry leader that thrives on innovation."))
        self.label_14.setText(_translate("MainWindow", "Welcome to GFLIX – The Ultimate Destination for Movie Enthusiasts!"))
        self.label_16.setText(_translate("MainWindow", "GFLIX is more than just a cinema – we bring you a world-class movie experience, where cutting-edge technology meets an immersive entertainment space.      Founded with the mission to elevate cinematic enjoyment, GFLIX is committed to delivering unforgettable moments to every audience member."))
        self.label_17.setText(_translate("MainWindow", "Premium Services – Comfortable seating"))
        self.label_19.setText(_translate("MainWindow", "High-quality Food & Beverages"))
        self.label_20.setText(_translate("MainWindow", "GFLIX offers exclusive events that elevate your movie experience beyond the ordinary. Enjoy VIP screenings, thrilling blockbuster premieres, and themed movie nights designed for true film enthusiasts. Whether it’s a red-carpet event, fan meetup, or special director’s cut screening, every occasion at GFLIX promises unforgettable moments."))
        self.pushButtonLearnMore1.setText(_translate("MainWindow", "Learn More"))
        self.label_22.setText(_translate("MainWindow", "At GFLIX, comfort is our priority. Our plush, ergonomic seats provide ample legroom and superior support, ensuring a relaxing and immersive movie experience. Whether you choose standard recliners or VIP loungers, each seat is designed for maximum comfort and enjoyment."))
        self.label_23.setText(_translate("MainWindow", " unforgettable moments."))
        self.label_21.setText(_translate("MainWindow", "Founded with the mission to elevate cinematic enjoyment, GFLIX is committed to delivering unforgettable moments to every audience member."))
        self.label_18.setText(_translate("MainWindow", "Hollywood-Standard Screens"))
        self.label_26.setText(_translate("MainWindow", "Exclusive Events"))
        self.label_28.setText(_translate("MainWindow", "superior support, ensuring a relaxing and immersive movie experience. Whether you choose      standard recliners or VIP loungers, each seat is designed for maximum comfort and enjoyment."))
        self.label_29.setText(_translate("MainWindow", "standard recliners or VIP loungers, each seat is designed for maximum comfort and enjoyment."))
        self.label_30.setText(_translate("MainWindow", "thrilling blockbuster premieres, and themed movie nights designed for true film enthusiasts. Whether it’s a red-carpet event, fan meetup, or special director’s cut screening, every occasion at GFLIX promises unforgettable moments."))
        self.label_31.setText(_translate("MainWindow", "red-carpet event, fan meetup, or special director’s cut screening, every occasion at GFLIX promises"))
        self.pushButtonLearnMore2.setText(_translate("MainWindow", "Learn More"))
        self.label_24.setText(_translate("MainWindow", " visuals, vibrant colors, and stunning detail. Every frame is brought to life with exceptional sharpness and     realism, ensuring a truly immersive cinematic experience."))
        self.label_32.setText(_translate("MainWindow", "GFLIX features Hollywood-standard screens with cutting-edge projection technology, delivering crystal-clear             visuals, vibrant colors, and stunning detail. Every frame is brought to life with exceptional sharpness and realism, ensuring a truly immersive cinematic experience."))
        self.label_27.setText(_translate("MainWindow", "realism, ensuring a truly immersive cinematic experience."))
        self.pushButtonLearnMore3.setText(_translate("MainWindow", "Learn More"))
        self.label_33.setText(_translate("MainWindow", "refreshing drinks, and handcrafted desserts, every item is carefully selected for maximum flavor "))
        self.label_34.setText(_translate("MainWindow", "At GFLIX, we offer a diverse menu of high-quality food and beverages to enhance your movie             experience. From freshly popped gourmet popcorn and signature snacks to premium coffee, refreshing drinks, and handcrafted desserts, every item is carefully selected for maximum flavor and enjoyment."))
        self.label_35.setText(_translate("MainWindow", "experience. From freshly popped gourmet popcorn and signature snacks to premium coffee,               refreshing drinks, and handcrafted desserts, every item is carefully selected for maximum flavor and enjoyment."))
        self.label_8.setText(_translate("MainWindow", "and enjoyment."))
        self.pushButtonLearnMore4.setText(_translate("MainWindow", "Learn More"))
        self.label_44.setText(_translate("MainWindow", "CONTACT US"))
        self.pushButtonfb.setText(_translate("MainWindow", "Facebook"))
        self.label_42.setText(_translate("MainWindow", "WE MAKE MOVIES BETTER"))
        self.label_43.setText(_translate("MainWindow", "© Copyright 2025 GFlix Theatres"))
        self.comboBox.setItemText(0, _translate("MainWindow", "SELECT THEATER   "))
        self.comboBox.setItemText(1, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(2, _translate("MainWindow", "HAI BÀ TRƯNG"))
        self.comboBox.setItemText(3, _translate("MainWindow", "QUỐC THANH"))
        self.comboBox.setItemText(4, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(5, _translate("MainWindow", "New Item"))
        self.pushButtonTicket.setText(_translate("MainWindow", "BUY TICKETS"))
        self.pushButtonBuyPop.setText(_translate("MainWindow", "BUY POPCORN"))
