# Form implementation generated from reading ui file 'D:\Final_Project_HTM\ui\BuyPopcorn.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 713)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"    border: none")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonShwtm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonShwtm.setGeometry(QtCore.QRect(20, 70, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonShwtm.setFont(font)
        self.pushButtonShwtm.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"    border: none")
        self.pushButtonShwtm.setObjectName("pushButtonShwtm")
        self.pushButtonDiscounts = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDiscounts.setGeometry(QtCore.QRect(820, 70, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDiscounts.setFont(font)
        self.pushButtonDiscounts.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"    border: none")
        self.pushButtonDiscounts.setObjectName("pushButtonDiscounts")
        self.pushButtonAboutUs = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonAboutUs.setGeometry(QtCore.QRect(910, 70, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonAboutUs.setFont(font)
        self.pushButtonAboutUs.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"    border: none")
        self.pushButtonAboutUs.setObjectName("pushButtonAboutUs")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 100, 1001, 561))
        font = QtGui.QFont()
        font.setItalic(True)
        font.setKerning(True)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("QScrollBar::sub-line:vertical {\n"
"    border:none;\n"
"    background-color:rgb(59,59,90);\n"
"    height: 15px;\n"
"    border-top-left-radius:7px;\n"
"    border-top-right-radius:7px;\n"
"    subcontrol-position:top;\n"
"    subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    background-color:rgb(255,0,127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"    background-color:rgb(185,0,92);\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border:none;\n"
"    background-color:rgb(59,59,90);\n"
"    height: 15px;\n"
"    border-top-left-radius:7px;\n"
"    border-top-right-radius:7px;\n"
"    subcontrol-position:bottom;\n"
"    subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"    background-color:rgb(255,0,127);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"    background-color:rgb(185,0,92);\n"
"}\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical{\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
"    background: none;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border:none;\n"
"    background-color:rgb(59,59,90);\n"
"    height: 15px;\n"
"    border-top-left-radius:7px;\n"
"    border-top-right-radius:7px;\n"
"    subcontrol-position:top;\n"
"    subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"    background-color:rgb(255,0,127);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"    background-color:rgb(185,0,92);\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border:none;\n"
"    background-color:rgb(59,59,90);\n"
"    height: 15px;\n"
"    border-top-left-radius:7px;\n"
"    border-top-right-radius:7px;\n"
"    subcontrol-position:bottom;\n"
"    subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"    background-color:rgb(255,0,127);\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"    background-color:rgb(185,0,92);\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal{\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal{\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -1920, 980, 2622))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(100, 2600))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setMouseTracking(False)
        self.frame.setTabletTracking(False)
        self.frame.setAcceptDrops(True)
        self.frame.setStyleSheet("    border: none")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(30, 810, 231, 261))
        self.label_4.setStyleSheet("border-radius: 10px;")
        self.label_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_4.setText("")
        self.label_4.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_4.setPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\../images/solo1.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(510, 810, 251, 261))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\../images/cple.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(parent=self.frame)
        self.label_10.setGeometry(QtCore.QRect(60, 740, 831, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.widget = QtWidgets.QWidget(parent=self.frame)
        self.widget.setGeometry(QtCore.QRect(280, 1030, 141, 41))
        self.widget.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 10, 51, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.labelSolo = QtWidgets.QLabel(parent=self.widget)
        self.labelSolo.setGeometry(QtCore.QRect(50, 10, 41, 21))
        self.labelSolo.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */border:none\n"
"}\n"
"")
        self.labelSolo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelSolo.setObjectName("labelSolo")
        self.label_11 = QtWidgets.QLabel(parent=self.frame)
        self.label_11.setGeometry(QtCore.QRect(70, 1110, 831, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_11.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(0, 1180, 981, 331))
        self.label_5.setStyleSheet("border-radius: 10px;")
        self.label_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_5.setText("")
        self.label_5.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_5.setPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\../images/Screenshot 2025-03-17 014916.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.label_12 = QtWidgets.QLabel(parent=self.frame)
        self.label_12.setGeometry(QtCore.QRect(100, 1520, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_12.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.frame)
        self.label_13.setGeometry(QtCore.QRect(370, 1520, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_13.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.frame)
        self.label_14.setGeometry(QtCore.QRect(610, 1520, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.widget_2 = QtWidgets.QWidget(parent=self.frame)
        self.widget_2.setGeometry(QtCore.QRect(780, 1020, 141, 41))
        self.widget_2.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 10, 51, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.labelCouple = QtWidgets.QLabel(parent=self.widget_2)
        self.labelCouple.setGeometry(QtCore.QRect(50, 10, 41, 21))
        self.labelCouple.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */border:none\n"
"}\n"
"")
        self.labelCouple.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelCouple.setObjectName("labelCouple")
        self.widget_3 = QtWidgets.QWidget(parent=self.frame)
        self.widget_3.setGeometry(QtCore.QRect(130, 1560, 141, 41))
        self.widget_3.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.widget_3)
        self.pushButton_7.setGeometry(QtCore.QRect(80, 10, 51, 20))
        self.pushButton_7.setObjectName("pushButton_7")
        self.labelCoke = QtWidgets.QLabel(parent=self.widget_3)
        self.labelCoke.setGeometry(QtCore.QRect(50, 10, 41, 21))
        self.labelCoke.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */border:none\n"
"}\n"
"")
        self.labelCoke.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelCoke.setObjectName("labelCoke")
        self.widget_4 = QtWidgets.QWidget(parent=self.frame)
        self.widget_4.setGeometry(QtCore.QRect(400, 1560, 141, 41))
        self.widget_4.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_9.setGeometry(QtCore.QRect(80, 10, 51, 20))
        self.pushButton_9.setObjectName("pushButton_9")
        self.labelSprite = QtWidgets.QLabel(parent=self.widget_4)
        self.labelSprite.setGeometry(QtCore.QRect(50, 10, 41, 21))
        self.labelSprite.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */border:none\n"
"}\n"
"")
        self.labelSprite.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelSprite.setObjectName("labelSprite")
        self.widget_5 = QtWidgets.QWidget(parent=self.frame)
        self.widget_5.setGeometry(QtCore.QRect(660, 1560, 141, 41))
        self.widget_5.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_11.setGeometry(QtCore.QRect(80, 10, 51, 20))
        self.pushButton_11.setObjectName("pushButton_11")
        self.labelFanta = QtWidgets.QLabel(parent=self.widget_5)
        self.labelFanta.setGeometry(QtCore.QRect(50, 10, 41, 21))
        self.labelFanta.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */border:none\n"
"}\n"
"")
        self.labelFanta.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelFanta.setObjectName("labelFanta")
        self.label_17 = QtWidgets.QLabel(parent=self.frame)
        self.label_17.setGeometry(QtCore.QRect(600, 1920, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_17.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.frame)
        self.label_18.setGeometry(QtCore.QRect(370, 1920, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_18.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.widget_6 = QtWidgets.QWidget(parent=self.frame)
        self.widget_6.setGeometry(QtCore.QRect(680, 1960, 141, 41))
        self.widget_6.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.widget_6)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.widget_6)
        self.pushButton_13.setGeometry(QtCore.QRect(80, 10, 51, 20))
        self.pushButton_13.setObjectName("pushButton_13")
        self.labelCaramel = QtWidgets.QLabel(parent=self.widget_6)
        self.labelCaramel.setGeometry(QtCore.QRect(50, 10, 41, 21))
        self.labelCaramel.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */border:none\n"
"}\n"
"")
        self.labelCaramel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelCaramel.setObjectName("labelCaramel")
        self.label_20 = QtWidgets.QLabel(parent=self.frame)
        self.label_20.setGeometry(QtCore.QRect(60, 1630, 831, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_20.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(parent=self.frame)
        self.label_21.setGeometry(QtCore.QRect(90, 1700, 211, 221))
        self.label_21.setStyleSheet("border-radius: 10px;")
        self.label_21.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_21.setText("")
        self.label_21.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_21.setPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\../images/str.webp"))
        self.label_21.setScaledContents(True)
        self.label_21.setWordWrap(False)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(parent=self.frame)
        self.label_22.setGeometry(QtCore.QRect(370, 1700, 211, 221))
        self.label_22.setStyleSheet("border-radius: 10px;")
        self.label_22.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_22.setText("")
        self.label_22.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_22.setPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\../images/cheese.webp"))
        self.label_22.setScaledContents(True)
        self.label_22.setWordWrap(False)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.frame)
        self.label_23.setGeometry(QtCore.QRect(660, 1700, 191, 221))
        self.label_23.setStyleSheet("border-radius: 10px;")
        self.label_23.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_23.setText("")
        self.label_23.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_23.setPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\../images/Screenshot 2025-03-17 012401.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setWordWrap(False)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.frame)
        self.label_24.setGeometry(QtCore.QRect(50, 1920, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_24.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.widget_7 = QtWidgets.QWidget(parent=self.frame)
        self.widget_7.setGeometry(QtCore.QRect(120, 1960, 141, 41))
        self.widget_7.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_7.setObjectName("widget_7")
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.widget_7)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.widget_7)
        self.pushButton_15.setGeometry(QtCore.QRect(80, 10, 51, 20))
        self.pushButton_15.setObjectName("pushButton_15")
        self.labelOriginal = QtWidgets.QLabel(parent=self.widget_7)
        self.labelOriginal.setGeometry(QtCore.QRect(50, 10, 41, 21))
        self.labelOriginal.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */border:none\n"
"}\n"
"")
        self.labelOriginal.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelOriginal.setObjectName("labelOriginal")
        self.widget_8 = QtWidgets.QWidget(parent=self.frame)
        self.widget_8.setGeometry(QtCore.QRect(400, 1960, 141, 41))
        self.widget_8.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    background: transparent;\n"
"    font-size: 16px;\n"
"    color: black;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.widget_8.setObjectName("widget_8")
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.widget_8)
        self.pushButton_16.setGeometry(QtCore.QRect(10, 10, 51, 21))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.widget_8)
        self.pushButton_17.setGeometry(QtCore.QRect(80, 10, 51, 20))
        self.pushButton_17.setObjectName("pushButton_17")
        self.labelCheese = QtWidgets.QLabel(parent=self.widget_8)
        self.labelCheese.setGeometry(QtCore.QRect(50, 10, 41, 21))
        self.labelCheese.setStyleSheet("QWidget {\n"
"    background-color: rgba(127, 140, 153, 150); /* Màu xám xanh với độ trong suốt */\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgba(46, 46, 100, 180); /* Viền xanh với độ trong suốt */border:none\n"
"}\n"
"")
        self.labelCheese.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelCheese.setObjectName("labelCheese")
        self.label_27 = QtWidgets.QLabel(parent=self.frame)
        self.label_27.setGeometry(QtCore.QRect(260, 840, 161, 161))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_27.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.frame)
        self.label_28.setGeometry(QtCore.QRect(770, 830, 171, 171))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(parent=self.frame)
        self.label_29.setGeometry(QtCore.QRect(-10, 0, 991, 331))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\../images/pop.jpg"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.label_59 = QtWidgets.QLabel(parent=self.frame)
        self.label_59.setGeometry(QtCore.QRect(0, 330, 981, 331))
        self.label_59.setText("")
        self.label_59.setPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\../images/crunch.jpg"))
        self.label_59.setScaledContents(True)
        self.label_59.setObjectName("label_59")
        self.pushButtonDiscounts_4 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonDiscounts_4.setGeometry(QtCore.QRect(10, 290, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonDiscounts_4.setFont(font)
        self.pushButtonDiscounts_4.setStyleSheet("background-color: transparent;\n"
"color: rgb(255, 255, 255);\n"
"    border: none")
        self.pushButtonDiscounts_4.setText("")
        self.pushButtonDiscounts_4.setObjectName("pushButtonDiscounts_4")
        self.label_60 = QtWidgets.QLabel(parent=self.frame)
        self.label_60.setGeometry(QtCore.QRect(30, 390, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_60.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(parent=self.frame)
        self.label_61.setGeometry(QtCore.QRect(20, 210, 281, 101))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(25)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_61.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(parent=self.frame)
        self.label_62.setGeometry(QtCore.QRect(180, 480, 611, 101))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_62.setFont(font)
        self.label_62.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_62.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_62.setWordWrap(True)
        self.label_62.setObjectName("label_62")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(20, 2040, 711, 281))
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: black;  /* Nền trắng */\n"
"    color: white;  /* Chữ đen */\n"
"    border-radius: 12px; /* Bo góc mềm */\n"
"    padding: 5px; /* Khoảng cách lề trong */\n"
"    border: 1px solid #ccc; /* Viền xám nhẹ */\n"
"}\n"
"\n"
"/* Header của bảng */\n"
"QHeaderView::section {\n"
"     /* Nền xám nhạt cho header */\n"
"    background-color: ;\n"
"    color: rgb(208, 208, 208);\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    border-radius: 0;\n"
"    padding: 6px;\n"
"    border: 1px solid #ccc; /* Viền xám nhẹ */\n"
"}\n"
"\n"
"/* Các ô trong bảng */\n"
"QTableWidget::item {\n"
"    border-bottom: 1px solid #ddd; /* Viền giữa các ô */\n"
"    padding: 6px;\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        item.setBackground(QtGui.QColor(113, 113, 170))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.label_44 = QtWidgets.QLabel(parent=self.frame)
        self.label_44.setGeometry(QtCore.QRect(290, 2340, 381, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_44.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_44.setObjectName("label_44")
        self.label_43 = QtWidgets.QLabel(parent=self.frame)
        self.label_43.setGeometry(QtCore.QRect(280, 2510, 411, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_43.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_18.setGeometry(QtCore.QRect(410, 2440, 141, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("background-color: transparent;\n"
"\n"
"    border: none")
        self.pushButton_18.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\../images/logoreal.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_18.setIcon(icon)
        self.pushButton_18.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_18.setObjectName("pushButton_18")
        self.label_42 = QtWidgets.QLabel(parent=self.frame)
        self.label_42.setGeometry(QtCore.QRect(270, 2480, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("background-color: transparent;\n"
"    border: none")
        self.label_42.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.pushButtonfb = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonfb.setGeometry(QtCore.QRect(420, 2400, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonfb.setFont(font)
        self.pushButtonfb.setStyleSheet("background-color:  rgb(255, 255, 255);\n"
"color:rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"    padding: 5px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\../images/fb.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonfb.setIcon(icon1)
        self.pushButtonfb.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonfb.setAutoRepeatDelay(305)
        self.pushButtonfb.setObjectName("pushButtonfb")
        self.line_2 = QtWidgets.QFrame(parent=self.frame)
        self.line_2.setGeometry(QtCore.QRect(0, 2350, 1001, 1))
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButtonPayment = QtWidgets.QPushButton(parent=self.frame)
        self.pushButtonPayment.setGeometry(QtCore.QRect(770, 2150, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonPayment.setFont(font)
        self.pushButtonPayment.setStyleSheet("background-color: rgb(173, 54, 68);\n"
"background-color: rgb(255, 157, 76);\n"
"color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\Final_Project_HTM\\ui\\../images/ic_popcorn.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonPayment.setIcon(icon2)
        self.pushButtonPayment.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonPayment.setAutoRepeatDelay(305)
        self.pushButtonPayment.setObjectName("pushButtonPayment")
        self.verticalLayout.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 60, 1001, 1))
        self.line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.pushButtonHome = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonHome.setGeometry(QtCore.QRect(20, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonHome.setFont(font)
        self.pushButtonHome.setStyleSheet("background-color: rgb(173, 54, 68);\n"
"color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px")
        self.pushButtonHome.setIcon(icon2)
        self.pushButtonHome.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonHome.setAutoRepeatDelay(305)
        self.pushButtonHome.setObjectName("pushButtonHome")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonShwtm.setText(_translate("MainWindow", "Showtimes"))
        self.pushButtonDiscounts.setText(_translate("MainWindow", "Discounts"))
        self.pushButtonAboutUs.setText(_translate("MainWindow", "About Us"))
        self.label_10.setText(_translate("MainWindow", "COMBO"))
        self.pushButton.setText(_translate("MainWindow", "-"))
        self.pushButton_2.setText(_translate("MainWindow", "+"))
        self.labelSolo.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "BEVERAGES"))
        self.label_12.setText(_translate("MainWindow", "COKE    37.000VND"))
        self.label_13.setText(_translate("MainWindow", "SPRITE  37.000VND"))
        self.label_14.setText(_translate("MainWindow", "FANTA  37.000VND"))
        self.pushButton_4.setText(_translate("MainWindow", "-"))
        self.pushButton_5.setText(_translate("MainWindow", "+"))
        self.labelCouple.setText(_translate("MainWindow", "0"))
        self.pushButton_6.setText(_translate("MainWindow", "-"))
        self.pushButton_7.setText(_translate("MainWindow", "+"))
        self.labelCoke.setText(_translate("MainWindow", "0"))
        self.pushButton_8.setText(_translate("MainWindow", "-"))
        self.pushButton_9.setText(_translate("MainWindow", "+"))
        self.labelSprite.setText(_translate("MainWindow", "0"))
        self.pushButton_10.setText(_translate("MainWindow", "-"))
        self.pushButton_11.setText(_translate("MainWindow", "+"))
        self.labelFanta.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "CARAMEL  60.000VND"))
        self.label_18.setText(_translate("MainWindow", "CHEESE  60.000"))
        self.pushButton_12.setText(_translate("MainWindow", "-"))
        self.pushButton_13.setText(_translate("MainWindow", "+"))
        self.labelCaramel.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "POPCORNS"))
        self.label_24.setText(_translate("MainWindow", "ORIGINAL  50.000VND"))
        self.pushButton_14.setText(_translate("MainWindow", "-"))
        self.pushButton_15.setText(_translate("MainWindow", "+"))
        self.labelOriginal.setText(_translate("MainWindow", "0"))
        self.pushButton_16.setText(_translate("MainWindow", "-"))
        self.pushButton_17.setText(_translate("MainWindow", "+"))
        self.labelCheese.setText(_translate("MainWindow", "0"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p>COMBO SOLO:<br/>1 Coke + 1 Pop</p><p>90.000VND</p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p>COMBO COUPLE:<br/>2 Coke + 1 Pop</p><p>110.000VND</p></body></html>"))
        self.label_60.setText(_translate("MainWindow", "Crunch, Munch, and Sip"))
        self.label_61.setText(_translate("MainWindow", "Food & Drink at GFilx"))
        self.label_62.setText(_translate("MainWindow", "GFlix goes far beyond classic concessions like popcorn and fountain drinks to give you an absolutely appetizing experience. We\'re always innovating and exploring new ways to bring the best food and drinks to our theatres. Select from the options below to learn more about the menu selections, locations and special offers."))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sản phẩm"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Số lượng"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Đơn giá"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Thành tiền"))
        self.label_44.setText(_translate("MainWindow", "CONTACT US"))
        self.label_43.setText(_translate("MainWindow", "© Copyright 2025 GFlix Theatres"))
        self.label_42.setText(_translate("MainWindow", "WE MAKE MOVIES BETTER"))
        self.pushButtonfb.setText(_translate("MainWindow", "Facebook"))
        self.pushButtonPayment.setText(_translate("MainWindow", "ORDER"))
        self.pushButtonHome.setText(_translate("MainWindow", "HOME"))
